import pandas as pd


configfile: "config/config.yaml"


samples = pd.read_table(config["samples"], comment="#", sep=r"\s+").set_index("sample")

include: "rules/download.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/expression.smk"
include: "rules/enrichment.smk"
include: "rules/multiqc.smk"


contrast = [c.replace(",", "_vs_") for c in config["contrasts"]]
cutoffs = config["padj_cutoffs"]


rule all:
    input:
        expand("results/qc/fastp/{sample}.html", sample=samples.index),
        expand("results/salmon/{sample}/quant.sf", sample=samples.index),
        "results/qc/multiqc_report.html",
        "results/deseq2/rldm.tsv",
        expand(
            "results/deseq2/{contrast}_padj{padj}.tsv", contrast=contrast, padj=cutoffs
        ),
        expand(
            "results/enrichment/{contrast}_padj{padj}_GO_{direction}.tsv",
            contrast=contrast,
            padj=cutoffs,
            direction=["up", "down"],
        ),
