import pandas as pd

configfile: "config/config.yaml"

samples = pd.read_table(config["samples"], comment="#").set_index("sample")

include: "workflow/rules/download.smk"
include: "workflow/rules/trimming.smk"
include: "workflow/rules/assembly.smk"
include: "workflow/rules/mapping.smk"
include: "workflow/rules/expression.smk"
include: "workflow/rules/multiqc.smk"

rule all:
    input:
        # --- fastp trimming QC ---
        expand("results/qc/fastp/{sample}.html", sample=samples.index),
        # --- Salmon quantification ---
        expand("results/salmon/{sample}/quant.sf", sample=samples.index),
        # --- Aggregated QC ---
        "results/qc/multiqc_report.html",
        # --- DESeq2 normalized counts ---
        "results/deseq2/rldm.tsv",
        # --- Differential expression ---
        expand("results/deseq2/{contrast}.tsv",
               contrast=[c.replace(",", "_vs_") for c in config["contrasts"]]),
        # --- GO enrichment ---
        expand("results/enrichment/{contrast}_GO.tsv",
               contrast=[c.replace(",", "_vs_") for c in config["contrasts"]]),
